/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package softwaredevcoursework;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.util.Base64;
import java.sql.Timestamp;
import java.util.Date;

/**
 *
 * @author theod
 */
public class SignIn extends javax.swing.JFrame {
    
    

    /**
     * Creates new form SignIn
     */
    public SignIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        uEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        uPass = new javax.swing.JPasswordField();
        signIn = new javax.swing.JButton();
        createAccount1 = new javax.swing.JButton();
        passwordRec = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel4.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sign In");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("E-mail");

        uEmail.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");

        uPass.setBackground(new java.awt.Color(255, 255, 255));

        signIn.setBackground(new java.awt.Color(153, 0, 0));
        signIn.setFont(new java.awt.Font("Segoe Print", 0, 36)); // NOI18N
        signIn.setForeground(new java.awt.Color(255, 255, 255));
        signIn.setText(">");
        signIn.setBorder(null);
        signIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInActionPerformed(evt);
            }
        });

        createAccount1.setBackground(new java.awt.Color(153, 0, 0));
        createAccount1.setForeground(new java.awt.Color(255, 255, 255));
        createAccount1.setText("Create Account");
        createAccount1.setBorder(null);
        createAccount1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccount1ActionPerformed(evt);
            }
        });

        passwordRec.setBackground(new java.awt.Color(153, 0, 0));
        passwordRec.setForeground(new java.awt.Color(255, 255, 255));
        passwordRec.setText("Password Recovery");
        passwordRec.setBorder(null);
        passwordRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordRecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(uPass, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(signIn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordRec, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createAccount1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(uEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(uPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(signIn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(createAccount1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordRec, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createAccount1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccount1ActionPerformed
        createAccount CreateAccount = new createAccount();
        CreateAccount.setVisible(true);
        
    }//GEN-LAST:event_createAccount1ActionPerformed

    private void signInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInActionPerformed
        
        String userEmail = uEmail.getText();
        String userPass = uPass.getText();
        Boolean adminCheck = false;
        
        String encryptedString = getEncodedString(userPass);
        userPass = encryptedString;

        ResultSet userResultSet = UserTable.get(userEmail);
        ResultSet userResultSet1 = UserTable.getPass(userPass);
        ResultSet userResultSet2 = UserTable.checkAdmin(userEmail,adminCheck);

        

        try {
            
            

            String emailRegex = "^(.+)@(.+)$";
            



            if (userEmail.trim().equals("")){
                JOptionPane.showMessageDialog(this,"Please enter your email!");

            }else if (!userEmail.matches(emailRegex)){
                JOptionPane.showMessageDialog(this,"Email is not in valid format!");

            } else if (!userResultSet.next()){
                JOptionPane.showMessageDialog(this,"No account with this email has been found!");
                
            } else if (userPass.trim().equals("")){
                JOptionPane.showMessageDialog(this,"Please enter your password!");
                
                
            } else if (!userResultSet1.next()){
                JOptionPane.showMessageDialog(this,"Incorrect password!");
            
            } else if (!userResultSet2.next()){
                JOptionPane.showMessageDialog(this,"Signed in successfully!");
                Date date = new Date();
                long time = date.getTime();
                Timestamp ts = new Timestamp(time);
                
                
                userActivityTable.insert(userEmail, ts, null);
                MainScreenAdmin mainscreen = new MainScreenAdmin(userEmail);
                mainscreen.setVisible(true);
                this.setVisible(false);
                
            } else {
                
                JOptionPane.showMessageDialog(this,"Signed in successfully!");
                Date date = new Date();
                long time = date.getTime();
                Timestamp ts = new Timestamp(time);
                
                userActivityTable.insert(userEmail, ts, null);
                MainScreenUser mainScreenUser = new MainScreenUser(userEmail);
                mainScreenUser.setVisible(true);
                this.setVisible(false);
                

            }

        } catch (Exception ex) {
            System.out.println("Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_signInActionPerformed

    private void passwordRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordRecActionPerformed
        passwordRecovery passwordRec = new passwordRecovery();
        passwordRec.setVisible(true);
    }//GEN-LAST:event_passwordRecActionPerformed

    /**
     * @param args the command line arguments
     */
    private static String getEncodedString(String userPassEncrypted){
        return Base64.getEncoder().encodeToString(userPassEncrypted.getBytes());
    }
    
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignIn().setVisible(true);
            }
        });
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createAccount1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton passwordRec;
    private javax.swing.JButton signIn;
    private javax.swing.JTextField uEmail;
    private javax.swing.JPasswordField uPass;
    // End of variables declaration//GEN-END:variables
}
